export const PLANS = {
  trial: {
    books_limit: 1,
    formats: ['ebook', 'paperback_kdp'] as const,
    markets: ['pt-br'] as const,
    audiobook: false,
    ingramspark: false,
    dust_jacket: false,
    days: 14,
  },
  starter: {
    price_brl_cents: 10900,
    price_usd_cents: 2999,
    books_limit: 1,
    formats: ['ebook', 'paperback_kdp'] as const,
    markets: ['pt-br'] as const,
    audiobook: false,
    ingramspark: false,
    dust_jacket: false,
  },
  pro: {
    price_brl_cents: 26900,
    price_usd_cents: 7499,
    books_limit: 3,
    formats: ['ebook', 'paperback_kdp', 'hardcover_kdp', 'paperback_is', 'hardcover_is'] as const,
    markets: ['pt-br', 'en'] as const,
    audiobook: true,
    ingramspark: true,
    dust_jacket: true,
  },
  publisher: {
    price_brl_cents: 67900,
    price_usd_cents: 18999,
    books_limit: 8,
    formats: 'all' as const,
    markets: ['pt-br', 'en'] as const,
    audiobook: true,
    ingramspark: true,
    dust_jacket: true,
    white_label: true,
    api_access: true,
    pen_names: 10,
  },
} as const;
