export const PLANS = {
  trial: {
    books_limit: 1,
    formats: ['ebook', 'paperback_kdp'] as const,
    markets: ['pt-br'] as const,
    audiobook: false,
    ingramspark: false,
    dust_jacket: false,
    days: 14,
  },
  starter: {
    price_brl_cents: 9700,
    price_usd_cents: 2700,
    books_limit: 1,
    formats: ['ebook', 'paperback_kdp'] as const,
    markets: ['pt-br'] as const,
    audiobook: false,
    ingramspark: false,
    dust_jacket: false,
  },
  pro: {
    price_brl_cents: 19700,
    price_usd_cents: 5700,
    books_limit: 3,
    formats: ['ebook', 'paperback_kdp', 'hardcover_kdp', 'paperback_is', 'hardcover_is'] as const,
    markets: ['pt-br', 'en'] as const,
    audiobook: true,
    ingramspark: true,
    dust_jacket: true,
  },
  publisher: {
    price_brl_cents: 49700,
    price_usd_cents: 14700,
    books_limit: -1,
    formats: 'all' as const,
    markets: ['pt-br', 'en'] as const,
    audiobook: true,
    ingramspark: true,
    dust_jacket: true,
    white_label: true,
    api_access: true,
    pen_names: -1,
  },
} as const;
